-- MySQL Script generated by MySQL Workbench
-- Thu Feb 24 16:31:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imprim3D
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imprim3D
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imprim3D` DEFAULT CHARACTER SET utf8 ;
USE `imprim3D` ;

-- -----------------------------------------------------
-- Table `imprim3D`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imprim3D`.`commande` ;

CREATE TABLE IF NOT EXISTS `imprim3D`.`commande` (
  `idcommande` INT NOT NULL,
  `vendeur` INT NULL DEFAULT NULL,
  `acheteur` INT NULL DEFAULT NULL,
  `objet` INT NULL DEFAULT NULL,
  `statut` INT NULL DEFAULT NULL,
  `date_creation` DATETIME NULL DEFAULT NULL,
  `maj` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idcommande`),
  INDEX `commande_objet` (`objet` ASC) VISIBLE,
  INDEX `commande_vendeur` (`vendeur` ASC) VISIBLE,
  INDEX `commande_acheteur` (`acheteur` ASC) INVISIBLE,
  INDEX `commande_statut` (`statut` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imprim3D`.`vendeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imprim3D`.`vendeur` ;

CREATE TABLE IF NOT EXISTS `imprim3D`.`vendeur` (
  `idvendeur` INT NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `age` DATE NULL DEFAULT NULL,
  `genre` VARCHAR(45) NULL DEFAULT NULL,
  `date_arrive` DATE NULL DEFAULT NULL,
  `nb_vente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idvendeur`),
  CONSTRAINT `vendeur_commande`
    FOREIGN KEY (`idvendeur`)
    REFERENCES `imprim3D`.`commande` (`vendeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imprim3D`.`acheteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imprim3D`.`acheteur` ;

CREATE TABLE IF NOT EXISTS `imprim3D`.`acheteur` (
  `idacheteur` INT NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `age` DATE NULL DEFAULT NULL,
  `genre` VARCHAR(45) NULL DEFAULT NULL,
  `date_insci` DATE NULL DEFAULT NULL,
  `nb_commande` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idacheteur`),
  CONSTRAINT `acheteur_commande`
    FOREIGN KEY (`idacheteur`)
    REFERENCES `imprim3D`.`commande` (`acheteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imprim3D`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imprim3D`.`user` ;

CREATE TABLE IF NOT EXISTS `imprim3D`.`user` (
  `iduser` INT NOT NULL,
  `vendeur` INT NOT NULL,
  `acheteur` INT NOT NULL,
  PRIMARY KEY (`iduser`, `vendeur`, `acheteur`),
  INDEX `user_vendeur` (`vendeur` ASC) INVISIBLE,
  INDEX `user_acheteur` (`acheteur` ASC) VISIBLE,
  CONSTRAINT `user_vendeur`
    FOREIGN KEY (`vendeur`)
    REFERENCES `imprim3D`.`vendeur` (`idvendeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_acheteur`
    FOREIGN KEY (`acheteur`)
    REFERENCES `imprim3D`.`acheteur` (`idacheteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imprim3D`.`objet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imprim3D`.`objet` ;

CREATE TABLE IF NOT EXISTS `imprim3D`.`objet` (
  `idobjet` INT NOT NULL,
  `matiere` INT NULL,
  `couleur` INT NULL,
  `longueur` INT NULL DEFAULT NULL,
  `largeur` INT NULL DEFAULT NULL,
  `profondeur` INT NULL DEFAULT NULL,
  `prix` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idobjet`),
  INDEX `objet_couleur` (`couleur` ASC) INVISIBLE,
  INDEX `objet_matiere` (`matiere` ASC) VISIBLE,
  CONSTRAINT `objet_commande`
    FOREIGN KEY (`idobjet`)
    REFERENCES `imprim3D`.`commande` (`objet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imprim3D`.`statut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imprim3D`.`statut` ;

CREATE TABLE IF NOT EXISTS `imprim3D`.`statut` (
  `idstatut` INT NOT NULL AUTO_INCREMENT,
  `type_statut` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idstatut`),
  CONSTRAINT `statut_commande`
    FOREIGN KEY (`idstatut`)
    REFERENCES `imprim3D`.`commande` (`statut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imprim3D`.`matiere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imprim3D`.`matiere` ;

CREATE TABLE IF NOT EXISTS `imprim3D`.`matiere` (
  `idmatiere` INT NOT NULL,
  `type_matiere` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmatiere`),
  CONSTRAINT `matiere_objet`
    FOREIGN KEY (`idmatiere`)
    REFERENCES `imprim3D`.`objet` (`matiere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imprim3D`.`couleur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imprim3D`.`couleur` ;

CREATE TABLE IF NOT EXISTS `imprim3D`.`couleur` (
  `idcouleur` INT NOT NULL,
  `couleurcol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcouleur`),
  CONSTRAINT `couleur_objet`
    FOREIGN KEY (`idcouleur`)
    REFERENCES `imprim3D`.`objet` (`couleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `imprim3D`.`commande`
-- -----------------------------------------------------
START TRANSACTION;
USE `imprim3D`;
INSERT INTO `imprim3D`.`commande` (`idcommande`, `vendeur`, `acheteur`, `objet`, `statut`, `date_creation`, `maj`) VALUES (1, 1, 1, 1, 1, '2022-03-15', '2022-03-22');

COMMIT;


-- -----------------------------------------------------
-- Data for table `imprim3D`.`vendeur`
-- -----------------------------------------------------
START TRANSACTION;
USE `imprim3D`;
INSERT INTO `imprim3D`.`vendeur` (`idvendeur`, `nom`, `age`, `genre`, `date_arrive`, `nb_vente`) VALUES (1, 'Robert', '51', 'Homme', '2021-08-09', 29);

COMMIT;


-- -----------------------------------------------------
-- Data for table `imprim3D`.`acheteur`
-- -----------------------------------------------------
START TRANSACTION;
USE `imprim3D`;
INSERT INTO `imprim3D`.`acheteur` (`idacheteur`, `nom`, `age`, `genre`, `date_insci`, `nb_commande`) VALUES (1, 'Michel', '62', 'Homme', '2018-07-21', 16);

COMMIT;


-- -----------------------------------------------------
-- Data for table `imprim3D`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `imprim3D`;
INSERT INTO `imprim3D`.`user` (`iduser`, `vendeur`, `acheteur`) VALUES (1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `imprim3D`.`objet`
-- -----------------------------------------------------
START TRANSACTION;
USE `imprim3D`;
INSERT INTO `imprim3D`.`objet` (`idobjet`, `matiere`, `couleur`, `longueur`, `largeur`, `profondeur`, `prix`) VALUES (1, 1, 1, 10, 10, 10, 20);

COMMIT;


-- -----------------------------------------------------
-- Data for table `imprim3D`.`statut`
-- -----------------------------------------------------
START TRANSACTION;
USE `imprim3D`;
INSERT INTO `imprim3D`.`statut` (`idstatut`, `type_statut`) VALUES (1, 'ANNULE');
INSERT INTO `imprim3D`.`statut` (`idstatut`, `type_statut`) VALUES (2, 'CONFIRME');
INSERT INTO `imprim3D`.`statut` (`idstatut`, `type_statut`) VALUES (3, 'ARCHIVE');
INSERT INTO `imprim3D`.`statut` (`idstatut`, `type_statut`) VALUES (4, 'EN COURS');
INSERT INTO `imprim3D`.`statut` (`idstatut`, `type_statut`) VALUES (5, 'TERMINE');

COMMIT;


-- -----------------------------------------------------
-- Data for table `imprim3D`.`matiere`
-- -----------------------------------------------------
START TRANSACTION;
USE `imprim3D`;
INSERT INTO `imprim3D`.`matiere` (`idmatiere`, `type_matiere`) VALUES (1, 'PLA');
INSERT INTO `imprim3D`.`matiere` (`idmatiere`, `type_matiere`) VALUES (2, 'ABS');
INSERT INTO `imprim3D`.`matiere` (`idmatiere`, `type_matiere`) VALUES (3, 'PVA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `imprim3D`.`couleur`
-- -----------------------------------------------------
START TRANSACTION;
USE `imprim3D`;
INSERT INTO `imprim3D`.`couleur` (`idcouleur`, `couleurcol`) VALUES (1, 'noir');
INSERT INTO `imprim3D`.`couleur` (`idcouleur`, `couleurcol`) VALUES (2, 'blanc');
INSERT INTO `imprim3D`.`couleur` (`idcouleur`, `couleurcol`) VALUES (3, 'or');
INSERT INTO `imprim3D`.`couleur` (`idcouleur`, `couleurcol`) VALUES (4, 'argent');
INSERT INTO `imprim3D`.`couleur` (`idcouleur`, `couleurcol`) VALUES (5, 'violet');
INSERT INTO `imprim3D`.`couleur` (`idcouleur`, `couleurcol`) VALUES (6, 'vert');

COMMIT;

